# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8da2a48a139d0674c0ee939cb535dc91eecca18e7651a270cdb93b5de94fb517599562a6d7da71663b8b9509c6abdb76eb7b971a2f3904e9c391bac11b5ed483

test:
  secret_key_base: f0f39093242209a5ad82d7779c1841bd3f630140dffae5044e8d8da51bd2af04a63b18005d432f67958318799fadc2b90e1a8dbf264e7b6f77293cf29f6226ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
